version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Use Dockerfile.dev for development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/src/config:/app/src/config
    container_name: omniplayr_frontend
    ports:
      - "8223:8223"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true # Use polling for file changes, useful for development

  backend:
    build: ./backend
    container_name: omniplayr_backend
    volumes:
      - ./db:/db
      - ./backend/config:/app/config
      - ./user_storage:/user_storage
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/omniplayr
    ports:
      - "8224:8224"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: omniplayr_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: omniplayr
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped